TOPICLIST: 
#msgsync.cpp
  #sub
  - TOPICTYPE: "POSE_SUB_TOPIC_A"
    TOPICNAME: "/uav/mavros/vision_pose/pose"
    #gazebo-> /uav_gazebo/mavros/local_position/pose
    #vicon -> /uav/mavros/vision_pose/pose
    #field -> /uav/mavros/local_position/pose
    SUBORPUB:  0
  
  - TOPICTYPE: "TWIST_SUB_TOPIC_A"
    TOPICNAME: "/uav/mavros/local_position/velocity_local" 
    #gazebo-> /uav/mavros/local_position/velocity_local
    #vicon -> /vrpn_client_node/gh034_nano/twist
    #field -> (depend on led)
    SUBORPUB:  0
  
  - TOPICTYPE: "IMU_SUB_TOPIC_A"
    TOPICNAME: "/uav/mavros/imu/data" 
    #gazebo-> /uav/mavros/imu/data
    #vicon -> /uav/mavros/imu/data
    #field -> /uav/mavros/imu/data
    SUBORPUB:  0

  - TOPICTYPE: "POSE_SUB_TOPIC_B"
    TOPICNAME: "/vrpn_client_node/gh034_car/pose"
    #gazebo-> /vrpn_client_node/gh034_nano/pose (from virtual)
    #vicon -> /vrpn_client_node/gh034_nano/pose
    #field -> /imu_pose (w/tf)
    SUBORPUB:  0
  
  - TOPICTYPE: "TWIST_SUB_TOPIC_B"
    TOPICNAME: "/vrpn_client_node/gh034_car/twist"
    #gazebo-> /vrpn_client_node/gh034_nano/twist (from virtual)
    #vicon -> /vrpn_client_node/gh034_nano/twist
    #field -> /imu_odom (w/tf)
    SUBORPUB:  0

  - TOPICTYPE: "IMU_SUB_TOPIC_B"
    TOPICNAME: "/ugv/mavros/imu/data" 
    #gazebo-> /ugv/mavros/imu/data (from virtual)
    #vicon -> /ugv/mavros/imu/data
    #field -> /ugv/mavros/imu/data
    SUBORPUB:  0

  - TOPICTYPE: "ODOM_SUB_TOPIC_A"
    TOPICNAME: "/alan_state_estimation/led/uav/odom"    
    SUBORPUB:  0
  

# Remark: 
# these are the topic type for rosconfigs.hpp

# from rosconfigs.hpp Line 28-81
# support up to 10 topic each
# could add more via customizing hpp if needed

# #define CAMERA_SUB_TOPIC_A "CAMERA_SUB_TOPIC_A"
# #define CAMERA_SUB_TOPIC_B "CAMERA_SUB_TOPIC_B"
# #define CAMERA_SUB_TOPIC_C "CAMERA_SUB_TOPIC_C"
# #define CAMERA_SUB_TOPIC_D "CAMERA_SUB_TOPIC_D"
# #define CAMERA_SUB_TOPIC_E "CAMERA_SUB_TOPIC_E"
# #define CAMERA_SUB_TOPIC_F "CAMERA_SUB_TOPIC_F"
# #define CAMERA_SUB_TOPIC_G "CAMERA_SUB_TOPIC_G"
# #define CAMERA_SUB_TOPIC_H "CAMERA_SUB_TOPIC_H"
# #define CAMERA_SUB_TOPIC_I "CAMERA_SUB_TOPIC_I"
# #define CAMERA_SUB_TOPIC_J "CAMERA_SUB_TOPIC_J"

# #define DEPTH_SUB_TOPIC_A "DEPTH_SUB_TOPIC_A"
# #define DEPTH_SUB_TOPIC_B "DEPTH_SUB_TOPIC_B"
# #define DEPTH_SUB_TOPIC_C "DEPTH_SUB_TOPIC_C"
# #define DEPTH_SUB_TOPIC_D "DEPTH_SUB_TOPIC_D"
# #define DEPTH_SUB_TOPIC_E "DEPTH_SUB_TOPIC_E"
# #define DEPTH_SUB_TOPIC_F "DEPTH_SUB_TOPIC_F"
# #define DEPTH_SUB_TOPIC_G "DEPTH_SUB_TOPIC_G"
# #define DEPTH_SUB_TOPIC_H "DEPTH_SUB_TOPIC_H"
# #define DEPTH_SUB_TOPIC_I "DEPTH_SUB_TOPIC_I"
# #define DEPTH_SUB_TOPIC_J "DEPTH_SUB_TOPIC_J"

# #define POSE_SUB_TOPIC_A "POSE_SUB_TOPIC_A"
# #define POSE_SUB_TOPIC_B "POSE_SUB_TOPIC_B"
# #define POSE_SUB_TOPIC_C "POSE_SUB_TOPIC_C"
# #define POSE_SUB_TOPIC_D "POSE_SUB_TOPIC_D"
# #define POSE_SUB_TOPIC_E "POSE_SUB_TOPIC_E"
# #define POSE_SUB_TOPIC_F "POSE_SUB_TOPIC_F"
# #define POSE_SUB_TOPIC_G "POSE_SUB_TOPIC_G"
# #define POSE_SUB_TOPIC_H "POSE_SUB_TOPIC_H"
# #define POSE_SUB_TOPIC_I "POSE_SUB_TOPIC_I"
# #define POSE_SUB_TOPIC_J "POSE_SUB_TOPIC_J"

# #define POSE_PUB_TOPIC_A "POSE_PUB_TOPIC_A"
# #define POSE_PUB_TOPIC_B "POSE_PUB_TOPIC_B"
# #define POSE_PUB_TOPIC_C "POSE_PUB_TOPIC_C"
# #define POSE_PUB_TOPIC_D "POSE_PUB_TOPIC_D"
# #define POSE_PUB_TOPIC_E "POSE_PUB_TOPIC_E"
# #define POSE_PUB_TOPIC_F "POSE_PUB_TOPIC_F"
# #define POSE_PUB_TOPIC_G "POSE_PUB_TOPIC_G"
# #define POSE_PUB_TOPIC_H "POSE_PUB_TOPIC_H"
# #define POSE_PUB_TOPIC_I "POSE_PUB_TOPIC_I"
# #define POSE_PUB_TOPIC_J "POSE_PUB_TOPIC_J"

# #define IMAGE_PUB_TOPIC_A "IMAGE_PUB_TOPIC_A"
# #define IMAGE_PUB_TOPIC_B "IMAGE_PUB_TOPIC_B"
# #define IMAGE_PUB_TOPIC_C "IMAGE_PUB_TOPIC_C"
# #define IMAGE_PUB_TOPIC_D "IMAGE_PUB_TOPIC_D"
# #define IMAGE_PUB_TOPIC_E "IMAGE_PUB_TOPIC_R"
# #define IMAGE_PUB_TOPIC_F "IMAGE_PUB_TOPIC_F"
# #define IMAGE_PUB_TOPIC_G "IMAGE_PUB_TOPIC_G"
# #define IMAGE_PUB_TOPIC_H "IMAGE_PUB_TOPIC_H"
# #define IMAGE_PUB_TOPIC_I "IMAGE_PUB_TOPIC_I"
# #define IMAGE_PUB_TOPIC_J "IMAGE_PUB_TOPIC_J"

# # SUBORPUB -> 0 as SUB, 1 as PUB
